/**
 * Lean food map wrapper for Supabase Edge Functions.
 *
 * - FOODS_DATA_LEAN is generated by `scripts/generate-lean-food-map.ts`
 *   into `food-map-lean-data.ts` (subset of the full FOODS_DATA).
 * - This file provides:
 *   - FOODS_BY_ID_LEAN: id → Food lookup restricted to the lean list
 *   - resolveToLeanId: resolve arbitrary input to a lean id (or null)
 *   - resolveCanonicalFoodId: alias-aware resolver restricted to lean ids
 */

import type { Food } from "./food-map.ts";
import { resolveFoodId } from "./food-map.ts";
import { FOODS_DATA_LEAN } from "./food-map-lean-data.ts";

export { FOODS_DATA_LEAN };

export const FOODS_BY_ID_LEAN: Record<string, Food> = Object.freeze(
  Object.fromEntries(FOODS_DATA_LEAN.map((f) => [f.id, f])),
);

/**
 * Resolve an arbitrary input (id or name) to a canonical lean food id.
 * Returns null if the resolved id is not present in the lean map.
 */
export function resolveToLeanId(input: string): string | null {
  const id = resolveFoodId(input);
  if (id && FOODS_BY_ID_LEAN[id]) return id;
  return null;
}

/**
 * Resolve a canonical food id suitable for lean map lookups.
 * This uses the same alias/normalization rules as resolveFoodId,
 * but only returns ids that exist in FOODS_BY_ID_LEAN.
 */
export function resolveCanonicalFoodId(input: string): string | null {
  const id = resolveFoodId(input);
  if (id && FOODS_BY_ID_LEAN[id]) return id;
  return null;
}

